//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrateur
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanqueEntities : DbContext
    {
        public BanqueEntities()
            : base("name=BanqueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<historique_transaction> historique_transaction { get; set; }
        public virtual DbSet<parametre> parametres { get; set; }
        public virtual DbSet<solde_clients> solde_clients { get; set; }
        public virtual DbSet<type_compte> type_compte { get; set; }
        public virtual DbSet<type_transaction> type_transaction { get; set; }
    }
}
