//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrateur
{

    public partial class historique_transaction
    {
        public int id_transaction { get; set; }
        public string code_client_envoi { get; set; }
        public string compte_client_envoi { get; set; }
        public string code_client_recus { get; set; }
        public string compte_client_recus { get; set; }
        public decimal montant { get; set; }
        public System.DateTime date { get; set; }
        public int idtype_transaction { get; set; }
        public string no_paiement { get; set; }

        public virtual client client { get; set; }
        public virtual client client1 { get; set; }
        public virtual solde_clients solde_clients { get; set; }
        public virtual solde_clients solde_clients1 { get; set; }
        public virtual type_transaction type_transaction { get; set; }

        public int typeCompteEnvoi => solde_clients.idtype_compte;
        public int typeCompteRecus => solde_clients1.idtype_compte;
        public string showDate => $" | Date: {date}";
        public string showHistorique => SetMessage();

        public string SetMessage()
        {
            string message = "";

            if (idtype_transaction == Classes.TypeDeTransaction.Depot)
            {
                message = $"Dépot de {montant.ToString("0.00")}$ dans le compte {solde_clients.numero_compte}";
            }
            else if (idtype_transaction == Classes.TypeDeTransaction.Retrait)
            {
                message = $"Retrait de {montant.ToString("0.00")}$ du compte {solde_clients.numero_compte}";
            }
            else if (idtype_transaction == Classes.TypeDeTransaction.Transfert)
            {
                message = $"Transfert de {montant.ToString("0.00")}$ du compte {solde_clients.numero_compte} à {solde_clients1.numero_compte}";
            }
            else if (idtype_transaction == Classes.TypeDeTransaction.Paiement)
            {
                message = $"Paiement de {montant.ToString("0.00")}$ @Ref: {no_paiement}";
            }

            return message;
        }
    }
}
