//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrateur
{
    using System;
    using System.Collections.Generic;
    
    public partial class solde_clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public solde_clients()
        {
            this.historique_transaction = new HashSet<historique_transaction>();
            this.historique_transaction1 = new HashSet<historique_transaction>();
        }
    
        public string compte_client { get; set; }
        public string code_client { get; set; }
        public int idtype_compte { get; set; }
        public decimal solde { get; set; }
        public string numero_compte => $"# {compte_client.Split('_')[1]}";
        public string nom_compte => $"{type_compte.description} {numero_compte}";
        public string nom_compteComplet => $"{solde.ToString("0.00")}$ | {nom_compte}";
        public string nom_userMontant => $"{client.nom_complet} # {numero_compte} | {solde.ToString("0.00")}$";
        
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historique_transaction> historique_transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historique_transaction> historique_transaction1 { get; set; }
        public virtual type_compte type_compte { get; set; }
    }
}
