//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLocations
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int NoAudit { get; set; }
        public System.DateTime DateChangement { get; set; }
        public string ColChangement { get; set; }
        public string AncienneValeur { get; set; }
        public string NouvelleValeur { get; set; }
        public string LocationChangement { get; set; }
    }
}
