//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLocations
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.InfoPaiements = new HashSet<InfoPaiement>();
        }
    
        public string NoLocation { get; set; }
        public DateTime? DateLocation { get; set; }
        public DateTime? DatePaiement { get; set; }
        public decimal MontantPaiement { get; set; }
        public int NbrPaiement { get; set; }
        public string VINVehicule { get; set; }
        public string NoClient { get; set; }
        public string TermesLocation { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoPaiement> InfoPaiements { get; set; }
        public virtual TermesDeLocation TermesDeLocation { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
